# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  config.vm.provision "shell", inline: <<-SHELL
    wget https://dl.google.com/go/go1.14.3.linux-amd64.tar.gz
    tar -C /usr/local -xzf go1.14.3.linux-amd64.tar.gz
    mkdir -p /home/vagrant/go/src
    mkdir -p /home/vagrant/go/bin
    mkdir -p /home/vagrant/go/pkg
    echo 'export PATH=$PATH:/usr/local/go/bin' >> /home/vagrant/.profile
  SHELL
end
