# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 2.0.0"

SUPPORTED_OS = {
  "ubuntu1804" => {box: "bento/ubuntu-18.04", user: "vagrant"},
}

#$num_instances = 2
$num_instances = 1
$num_k8s_master = 1
$instance_name_prefix = "kube"
$vm_gui = false
$vm_cpus = 2
$shared_folders = {}
$forwarded_ports = {}
$subnet = "192.168.34"
$os = "ubuntu1804"

$box = SUPPORTED_OS[$os][:box]

Vagrant.configure("2") do |config|

  config.vm.box = $box
  config.ssh.username = SUPPORTED_OS[$os][:user]

  (1..$num_instances).each do |i|
    config.vm.define vm_name = "%s-%01d" % [$instance_name_prefix, i] do |node|

      node.vm.hostname = vm_name

      node.vm.provider :virtualbox do |vb|
        vb.cpus = $vm_cpus
        vb.gui = $vm_gui
        vb.linked_clone = true
        vb.customize ["modifyvm", :id, "--vram", "8"] # ubuntu defaults to 256 MB which is a waste of precious RAM
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      end

      ip = "#{$subnet}.#{i+100}"
      node.vm.network :private_network, ip: ip

      node.vm.provision "shell", run: "always", inline: "swapoff -a"

      if i == $num_k8s_master
        node.vm.provider :virtualbox do |vb|
          vb.memory = 2048
        end

        # node.vm.provision "shell", inline: <<-SHELL
        #   /vagrant/install_k8s.sh -n master -i eth1 -p flannel -u vagrant
        # SHELL

      else
        node.vm.provider :virtualbox do |vb|
          vb.memory = 2048
        end
      end

    end
  end
end
